name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Generate Documentation
      run: cargo doc --no-deps
      
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_PK }}

    # Add steps for building/testing your site here

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your_email@example.com'
        git fetch --depth=1
        git add -f target/doc
        git commit -m "Update GitHub Pages"
        git subtree split --prefix target/doc -b gh-pages
        git push -f git@github.com:lmorais-dev/quantify.git gh-pages:gh-pages
